// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Employee struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	EmpID string `json:"empId"`
}

type Mutation struct {
}

type Query struct {
}

type EmpData struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	EmpID string `json:"empId"`
}

type UserRequest struct {
	Email string `json:"email"`
}
